version: '2'
services:
  clickhouse:
        image: clickhouse/clickhouse-server:23.3
        ports:
          - 9000:9000
          - 8123:8123
  dev:
    build: .
    volumes:
     - .:/usr/app/
    ports:
      - 8080:8080
    environment:
      - DBT_HOST=${CLICKHOUSE_HOST}
      - DBT_USER=${CLICKHOUSE_USER}
      - DBT_PASSWORD=${TF_VAR_clickhouse_password}
